name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION

template: |
  # What's Changed

  $CHANGES

include-labels:
  - breaking change
  - enhancement
  - bug
  - documentation
  - chore
  - dependencies

categories:
  - title: ⚠️ Breaking Changes
    label: breaking change

  - title: 🔒 Security
    label: security

  - title: 🚀 Features
    label: enhancement

  - title: 🐛 Bug Fixes
    label: bug

  - title: 📖 Documentation
    label: documentation

  - title: 🧹 Housekeeping
    label: chore

  - title: 📦 Dependency Updates
    label: dependencies
