additional:
  - "describe"

files:
  - "!**/*"
  - ".csharpierignore"
  - ".editorconfig"
  - "GitVersion.yml"
  - "new-project.ps1"
  - "update-solution.ps1"
  - ".github/CODEOWNERS"
  - ".github/dependabot.yml"
  - ".github/workflows/dependabot-merge.yml"
  - ".github/workflows/update-license.yml"

  # you probably want to exclude these files:
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
