# Every time I update this file without changing the content, I increment this counter.
# Counter: 2

additional:
  - analyzer
  - arguments
  - article.benchmarks
  - editorconfig
  - equaduct
  - extensions.hosting.winforms
  - extensions.strings
  - extensions.tasks
  - extensions.test
  - guard
  - healthchecks
  - http.correlation
  - logging.abstractions
  - logging.file
  - logging.measurement
  - logging.mstest
  - logging.xunit
  - projectbuilders
  - sequentialguid
  - sqlprettier

files:
  - "!**/*"
  - ".commitlintrc"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - ".github/CODEOWNERS"
  - ".github/dependabot.yml"
  - ".github/FUNDING.yml"
  - ".github/release-drafter.yml"
  - ".github/ISSUE_TEMPLATE/**/*"
  - ".github/PULL_REQUEST_TEMPLATE/**/*"
  - ".github/workflows/update-license.yml"

  # you probably want to exclude these files:
  - "!.github/workflows/dependabot-merge.yml"
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
