# Every time I update this file without changing the content, I increment this counter.
# Counter: 2

files:
  - "!**/*"
  - ".commitlintrc"
  - ".gitattributes"
  - ".gitignore"
  - "GitVersion.yml"
  - ".github/CODEOWNERS"
  - ".github/dependabot.yml"
  - ".github/FUNDING.yml"
  - ".github/release-drafter.yml"
  - ".github/ISSUE_TEMPLATE/**/*"
  - ".github/PULL_REQUEST_TEMPLATE/**/*"
  - ".github/workflows/update-license.yml"

  # you probably want to exclude these files:
  - "!.github/workflows/dependabot-merge.yml"
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"
