name: Auto Merge Minor Upgrades

on:
  pull_request:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT }}
          command: squash and merge
